spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microservices-with-spring-boot?currentSchema=course-app&useTimezone=true&serverTimezone=UTC
    username: admin
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  application:
    name: course-service

server:
  port: 8001